name: Build and Push Docker

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    uses: Gergo3/nvim-docker-workflows/.github/workflows/docker-build.yml@master
    with:
      image-name: nvim-python
    secrets: inherit

